imports:
    - php

tools:
    # PHP
    php_sim:                true
    php_code_sniffer:       true
    php_hhvm:               true
    php_mess_detector:      true
    php_pdepend:            true
    php_loc:                true
